--------------------------------------------------------
--  File created - Friday-February-21-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence JOB_MASTER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VBATCH"."JOB_MASTER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table JOB_MASTER
--------------------------------------------------------

  CREATE TABLE "VBATCH"."JOB_MASTER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Table JOB_STEPS_XREF
--------------------------------------------------------

  CREATE TABLE "VBATCH"."JOB_STEPS_XREF" 
   (	"ID" NUMBER, 
	"JOB_MASTER_ID" NUMBER, 
	"JOB_SEQ" NUMBER, 
	"DESCRIPTION" VARCHAR2(150 BYTE), 
	"STEP_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Table STEPS
--------------------------------------------------------

  CREATE TABLE "VBATCH"."STEPS" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"EXTRACT_MAX_REC_PER_FILE" NUMBER, 
	"EXTRACT_COMMIT_FREQ" NUMBER, 
	"EXTRACT_SQL" VARCHAR2(4000 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"OUTPUT_FILE_FORMAT" VARCHAR2(10 BYTE), 
	"OUTPUT_FILENAME_PREFIX" VARCHAR2(100 BYTE), 
	"OUTPUT_FILENAME_POSTFIX" VARCHAR2(100 BYTE), 
	"JAVA_BEAN_PATH" VARCHAR2(100 BYTE), 
	"PARAM1" VARCHAR2(100 BYTE), 
	"PARAM2" VARCHAR2(50 BYTE), 
	"PARAM3" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;

   COMMENT ON COLUMN "VBATCH"."STEPS"."TYPE" IS 'Type of step (Extract, Transform, etc)';
--------------------------------------------------------
--  DDL for Table VBATCH_LOG
--------------------------------------------------------

  CREATE TABLE "VBATCH"."VBATCH_LOG" 
   (	"SEQ_NBR" NUMBER, 
	"ID" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"VBATCH_LOG_END_DT" DATE, 
	"VBATCH_LOG_START_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Table VBATCH_LOG_DTL
--------------------------------------------------------

  CREATE TABLE "VBATCH"."VBATCH_LOG_DTL" 
   (	"ID" NUMBER, 
	"VBATCH_LOG_ID" NUMBER, 
	"SEQ_NBR" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"DTL_END_DT" DATE, 
	"DTL_START_DT" DATE, 
	"ERROR_MSG" VARCHAR2(500 BYTE), 
	"JOB_ID" NUMBER, 
	"JOB_SEQ" NUMBER, 
	"STEP_ID" NUMBER, 
	"STEP_NAME" NUMBER, 
	"STEP_TYPE" VARCHAR2(25 BYTE), 
	"NUM_RECORDS" NUMBER, 
	"EXTRACT_SQL" VARCHAR2(4000 BYTE), 
	"EXTRACT_MAX_RECS_PER_FILE" NUMBER, 
	"EXTRACT_COMMIT_FREQ" NUMBER, 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"OUTPUT_FILE_FORMAT" VARCHAR2(20 BYTE), 
	"OUTPUT_FILENAME_PREFIX" VARCHAR2(100 BYTE), 
	"OUTPUT_FILENAME_SUFFIX" VARCHAR2(100 BYTE), 
	"JAVA_BEAN_PATH" VARCHAR2(100 BYTE), 
	"PARAM1" VARCHAR2(50 BYTE), 
	"PARAM2" VARCHAR2(50 BYTE), 
	"PARAM3" VARCHAR2(50 BYTE), 
	"MIN_OK1" VARCHAR2(50 BYTE), 
	"MAX_OK2" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Table VBATCH_LOG_FILE_OUTPUT
--------------------------------------------------------

  CREATE TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" 
   (	"ID" NUMBER, 
	"VBATCH_LOG_ID" NUMBER, 
	"VBATCH_LOG_SEQ_NBR" NUMBER, 
	"SEQ_NBR" NUMBER, 
	"VBATCH_LOG_SEQ_NBR_1" NUMBER, 
	"VBATCH_LOG_ID_1" NUMBER, 
	"FILENAME" VARCHAR2(100 BYTE), 
	"NUM_RECORDS" NUMBER, 
	"CREATE_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Table VBATCH_LOG_OK_DTL
--------------------------------------------------------

  CREATE TABLE "VBATCH"."VBATCH_LOG_OK_DTL" 
   (	"ID" NUMBER, 
	"VBATCH_LOG_ID" NUMBER, 
	"VBATCH_LOG_SEQ_NBR" NUMBER, 
	"SEQ_NBR" NUMBER, 
	"PK1" NUMBER, 
	"PK2" NUMBER, 
	"PK3" NUMBER, 
	"OK" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Table VBATCH_PDI_LOG
--------------------------------------------------------

  CREATE TABLE "VBATCH"."VBATCH_PDI_LOG" 
   (	"ID_BATCH" NUMBER(*,0), 
	"CHANNEL_ID" VARCHAR2(255 BYTE), 
	"TRANSNAME" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(15 BYTE), 
	"LINES_READ" NUMBER(*,0), 
	"LINES_WRITTEN" NUMBER(*,0), 
	"LINES_UPDATED" NUMBER(*,0), 
	"LINES_INPUT" NUMBER(*,0), 
	"LINES_OUTPUT" NUMBER(*,0), 
	"LINES_REJECTED" NUMBER(*,0), 
	"ERRORS" NUMBER(*,0), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"LOGDATE" DATE, 
	"DEPDATE" DATE, 
	"REPLAYDATE" DATE, 
	"LOG_FIELD" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" 
 LOB ("LOG_FIELD") STORE AS BASICFILE (
  TABLESPACE "VBATCH_DEV" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into VBATCH.JOB_MASTER
SET DEFINE OFF;
REM INSERTING into VBATCH.JOB_STEPS_XREF
SET DEFINE OFF;
REM INSERTING into VBATCH.STEPS
SET DEFINE OFF;
REM INSERTING into VBATCH.VBATCH_LOG
SET DEFINE OFF;
REM INSERTING into VBATCH.VBATCH_LOG_DTL
SET DEFINE OFF;
REM INSERTING into VBATCH.VBATCH_LOG_FILE_OUTPUT
SET DEFINE OFF;
REM INSERTING into VBATCH.VBATCH_LOG_OK_DTL
SET DEFINE OFF;
REM INSERTING into VBATCH.VBATCH_PDI_LOG
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."ID" ON "VBATCH"."STEPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index IDX_VBATCH_PDI_LOG_1
--------------------------------------------------------

  CREATE INDEX "VBATCH"."IDX_VBATCH_PDI_LOG_1" ON "VBATCH"."VBATCH_PDI_LOG" ("ID_BATCH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index IDX_VBATCH_PDI_LOG_2
--------------------------------------------------------

  CREATE INDEX "VBATCH"."IDX_VBATCH_PDI_LOG_2" ON "VBATCH"."VBATCH_PDI_LOG" ("ERRORS", "STATUS", "TRANSNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index JOB_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."JOB_MASTER_PK" ON "VBATCH"."JOB_MASTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index JOB_STEPS_XREF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."JOB_STEPS_XREF_PK" ON "VBATCH"."JOB_STEPS_XREF" ("ID", "JOB_MASTER_ID", "JOB_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index VBATCH_LOG_DTL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."VBATCH_LOG_DTL_PK" ON "VBATCH"."VBATCH_LOG_DTL" ("ID", "VBATCH_LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index VBATCH_LOG_FILE_OUTPUT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."VBATCH_LOG_FILE_OUTPUT_PK" ON "VBATCH"."VBATCH_LOG_FILE_OUTPUT" ("ID", "VBATCH_LOG_ID", "VBATCH_LOG_SEQ_NBR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index VBATCH_LOG_OK_DTL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."VBATCH_LOG_OK_DTL_PK" ON "VBATCH"."VBATCH_LOG_OK_DTL" ("ID", "VBATCH_LOG_ID", "VBATCH_LOG_SEQ_NBR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  DDL for Index VBATCH_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VBATCH"."VBATCH_LOG_PK" ON "VBATCH"."VBATCH_LOG" ("SEQ_NBR", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
--------------------------------------------------------
--  Constraints for Table JOB_MASTER
--------------------------------------------------------

  ALTER TABLE "VBATCH"."JOB_MASTER" ADD CONSTRAINT "JOB_MASTER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."JOB_MASTER" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."JOB_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."JOB_MASTER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOB_STEPS_XREF
--------------------------------------------------------

  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" ADD CONSTRAINT "JOB_STEPS_XREF_PK" PRIMARY KEY ("ID", "JOB_MASTER_ID", "JOB_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" MODIFY ("STEP_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" MODIFY ("JOB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" MODIFY ("JOB_MASTER_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STEPS
--------------------------------------------------------

  ALTER TABLE "VBATCH"."STEPS" ADD CONSTRAINT "ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("PARAM3" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("PARAM2" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("PARAM1" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("JAVA_BEAN_PATH" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("OUTPUT_FILENAME_POSTFIX" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("OUTPUT_FILENAME_PREFIX" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("OUTPUT_FILE_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("EXTRACT_COMMIT_FREQ" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("EXTRACT_MAX_REC_PER_FILE" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."STEPS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VBATCH_LOG
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG" ADD CONSTRAINT "VBATCH_LOG_PK" PRIMARY KEY ("SEQ_NBR", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."VBATCH_LOG" MODIFY ("VBATCH_LOG_START_DT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG" MODIFY ("VBATCH_LOG_END_DT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG" MODIFY ("SEQ_NBR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VBATCH_LOG_DTL
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" ADD CONSTRAINT "VBATCH_LOG_DTL_PK" PRIMARY KEY ("ID", "VBATCH_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("MAX_OK2" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("MIN_OK1" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("PARAM3" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("PARAM2" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("PARAM1" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("JAVA_BEAN_PATH" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("OUTPUT_FILENAME_SUFFIX" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("OUTPUT_FILENAME_PREFIX" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("OUTPUT_FILE_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("EXTRACT_COMMIT_FREQ" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("EXTRACT_MAX_RECS_PER_FILE" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("EXTRACT_SQL" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("NUM_RECORDS" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("STEP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("STEP_NAME" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("STEP_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("JOB_SEQ" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("ERROR_MSG" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("DTL_START_DT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("DTL_END_DT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("SEQ_NBR" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("VBATCH_LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VBATCH_LOG_FILE_OUTPUT
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" ADD CONSTRAINT "VBATCH_LOG_FILE_OUTPUT_PK" PRIMARY KEY ("ID", "VBATCH_LOG_ID", "VBATCH_LOG_SEQ_NBR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("NUM_RECORDS" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("VBATCH_LOG_ID_1" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("VBATCH_LOG_SEQ_NBR_1" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("SEQ_NBR" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("VBATCH_LOG_SEQ_NBR" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("VBATCH_LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VBATCH_LOG_OK_DTL
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" ADD CONSTRAINT "VBATCH_LOG_OK_DTL_PK" PRIMARY KEY ("ID", "VBATCH_LOG_ID", "VBATCH_LOG_SEQ_NBR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VBATCH_DEV"  ENABLE;
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("OK" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("PK3" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("PK2" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("PK1" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("SEQ_NBR" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("VBATCH_LOG_SEQ_NBR" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("VBATCH_LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table JOB_STEPS_XREF
--------------------------------------------------------

  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" ADD CONSTRAINT "JOB_STEPS_XREF_JOB_MASTER_FK" FOREIGN KEY ("JOB_MASTER_ID")
	  REFERENCES "VBATCH"."JOB_MASTER" ("ID") ENABLE;
  ALTER TABLE "VBATCH"."JOB_STEPS_XREF" ADD CONSTRAINT "JOB_STEPS_XREF_STEPS_FK" FOREIGN KEY ("STEP_ID")
	  REFERENCES "VBATCH"."STEPS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VBATCH_LOG_DTL
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG_DTL" ADD CONSTRAINT "VBATCH_LOG_DTL_VBATCH_LOG_FK" FOREIGN KEY ("SEQ_NBR", "ID")
	  REFERENCES "VBATCH"."VBATCH_LOG" ("SEQ_NBR", "ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VBATCH_LOG_FILE_OUTPUT
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" ADD CONSTRAINT "VBATCH_LOG_FILE_OUTPUT_FK1" FOREIGN KEY ("VBATCH_LOG_SEQ_NBR_1", "VBATCH_LOG_ID_1")
	  REFERENCES "VBATCH"."VBATCH_LOG" ("SEQ_NBR", "ID") ENABLE;
  ALTER TABLE "VBATCH"."VBATCH_LOG_FILE_OUTPUT" ADD CONSTRAINT "VBATCH_LOG_FILE_OUTPUT_FK2" FOREIGN KEY ("SEQ_NBR", "ID")
	  REFERENCES "VBATCH"."VBATCH_LOG" ("SEQ_NBR", "ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VBATCH_LOG_OK_DTL
--------------------------------------------------------

  ALTER TABLE "VBATCH"."VBATCH_LOG_OK_DTL" ADD CONSTRAINT "VBATCH_LOG_OK_DTL_FK" FOREIGN KEY ("SEQ_NBR", "ID")
	  REFERENCES "VBATCH"."VBATCH_LOG" ("SEQ_NBR", "ID") ENABLE;
